### PR TITLE
Edge Impulse standalone inferencing examples fixes

### PR DESCRIPTION
**Pull request by mmajchrzycki**
This PR adds a few fixes in the EI standalone inferencing examples:
* adds support for different models (audio, image) in the CMSIS example
* adds support for non-image models in the Ethos example
* fixes linker scripts and available memory in both examples
* improves console output with the inferencing details in both examples

### CODE REVIEW

**Comment by kris-himax** [comment]
Hi @mmajchrzycki ,

At ei_standalone_inferencing_cmsis example, I think you want to change the model example from IMU to audio example.
But I think you may forgot to update the model which is still the old IMU model. And the [ei_classifier_inferencing_categories](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/EPII_CM55M_APP_S/app/scenario_app/ei_standalone_inferencing_cmsis/ei-model/model-parameters/model_variables.h#L32) are still  "drink", "fistbump", "idle", "snake", "updown", "wave".

At ei_standalone_inferencing_ethos example, I face build error at ei_standalone_inferencing_ethos.cpp 
Screenshot from 2024-07-29 17-23-59
And I think the [ethosu_flush_dcache](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/EPII_CM55M_APP_S/app/scenario_app/ei_standalone_inferencing_ethos/ei-model/edge-impulse-sdk/porting/ethos-core-driver/src/ethosu_driver.c#L130) and [ethosu_invalidate_dcache](https://github.com/HimaxWiseEyePlus/Seeed_Grove_Vision_AI_Module_V2/blob/main/EPII_CM55M_APP_S/app/scenario_app/ei_standalone_inferencing_ethos/ei-model/edge-impulse-sdk/porting/ethos-core-driver/src/ethosu_driver.c#L140) at ethosu_driver.c should be filled Himax SDK and can not be UNUSED.

Thanks
Kris

**Comment by kris-himax** [comment]
Hi @mmajchrzycki 

I also tried to use arm tool chain not gnu tool chain to build ei_standalone_inferencing_ethos example.
Facing the error at cisdp_sensor.c 
Screenshot from 2024-07-30 14-04-08
I think that it just need to include following code.
```
#include "driver_interface.h"
#include "math.h"
```
But it still occur another errors.
Screenshot from 2024-07-30 14-07-14


Thanks,
Kris

**Comment by mmajchrzycki** [comment]
@kris-himax 
I reworked the examples a little bit. Now we have two examples:
* ei_standalone_inferencing - with KWS model, static input data, and enabled Ethos, good for non-vision models
* ei_standalone_inferencing_camera - with FOMO face detection model, uses live camera image, Ethos enabled, good for vision models

I will try to test them with the ARM toolchain.

**Comment by kris-himax** [comment]
@mmajchrzycki

1. The ethosu_driver.c is not yet updated. This will cause the output when inference the vela model to be different from that without passing the vela model. I think this issue should be updated while export your model from the Edge Impulse Studio website. Or every model will have the issue.

2. I think the ei_standalone_inferencing example with KWS model should give the input with live PDM MIC data, not static input data.
3. I have the question about training model from the Edge Impulse Studio website. 
What is the `generate features` related to training model? why should the generating features always be done before training model? If I did not do this process, I can not start to do the training.
4. And I know the Raw Features is the raw image data or audio data. What is the processing about image and audio data to generate processed features and did you train the model by this processed features?
Screenshot from 2024-07-31 09-26-27
5. What is the meaning about the figure of "Feature explorer"?
Screenshot from 2024-07-31 09-36-23

**Comment by mmajchrzycki** [comment]
@kris-himax 
1. The fix for dcache flush and invalidate is in progress. It will be implemented as a separate function in the SDK porting layer, see [here](https://github.com/edgeimpulse/Seeed_Grove_Vision_AI_Module_V2/blob/ei-examples-fixes/EPII_CM55M_APP_S/app/scenario_app/ei_standalone_inferencing/ei-model/edge-impulse-sdk/porting/himax-we2/ethosu_driver.c). Each model deployed as a Ethos lib or C++ lib from studio will include this fix.
2. We are leaving this usually up for users to implement the sensor functionality. The role of the standalone examples is to provide the minimal code to run the inference on the device. Any sensor code is application specific (so users would like to use IMU, some the included microphone others will be looking for different sensors.)
3. The `generate features` is a process of running your dataset through the DSP block. Your NN model is studio is not trained on the raw input data, but on the pre-processed. It is especially visible for non-image projects that uses MFE or other blocks. You can easily see that `features` are much smaller than `raw data`. For image data it also applies crop and resizes the images from dataset.
4. See our [docs](https://docs.edgeimpulse.com/docs/edge-impulse-studio/processing-blocks). Each block processed data differently. Image is the easiest example. If your model needs input image 160x160 pixels, but you have high-resolution images with an aspect ratio of 16:9, then Image block crops the images and resizes them.
5. See our [docs](https://docs.edgeimpulse.com/docs/edge-impulse-studio/processing-blocks/feature-explorer). In simple words, Feature explorer allows you to see if your features could be easily separated into classes. The better the separation, the higher the chance of training the model with high accuracy.

**Comment by kris-himax** [comment]
@mmajchrzycki 
Thanks for reply.
1. I see the update about cache function at ei_standalone_inferencing example, but the ei_standalone_inferencing_camera example is not yet updated at [here](https://github.com/edgeimpulse/Seeed_Grove_Vision_AI_Module_V2/tree/ei-examples-fixes/EPII_CM55M_APP_S/app/scenario_app/ei_standalone_inferencing_camera/ei-model/edge-impulse-sdk/porting/himax-we2)
2. I see. Can I confirm that while I export the audio or IMU model code from Edge Impulse Studio website, I just need to feed the raw audio or IMU data input without doing any pre-proccessing and then the classification can be worked?

**Comment by mmajchrzycki** [comment]
1. I didn't update the model as it was not affected with the issue, but I will do that just in case.
2. Yes, you just need to provide raw data. Pre-processing will be done automatically inside the `run_classifier` function. You can enable debug (the last argument set to true) and the you will see pre-processed features in the console output.

**Pull request merged**
